---
version: '3.8'
services:

  prd-nginx-app:
    image: docker-registry.theautomation.nl/coen/prd-nginx-app:latest
    container_name: prd-nginx-app
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      home-services:
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  prd-certbot-app:
    image: docker-registry.theautomation.nl/coen/prd-certbot-app:latest
    container_name: prd-certbot-app
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - prd-certbot-app-data:/var/lib/letsencrypt
    networks:
      home-services:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# VOLUMES
volumes:

  prd-certbot-app-data:
    name: prd-certbot-app-data

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16


