---
version: "3.8"
services:
  nginx:
    image: docker-registry.theautomation.nl/coen/prd-nginx-certbot-app:latest
    container_name: prd-nginx-certbot-app
    restart: unless-stopped
    env_file: prd-nginx-certbot-app.env
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  reverse-proxy:
    driver: bridge
    name: reverse-proxy
    ipam:
      config:
        - subnet: 172.22.0.0/16
