---
version: '3.8'
services:

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: prd-nginx-certbot-app
    restart: unless-stopped
    env_file: prd-nginx-certbot-app.env
    ports:
      - 80:80
      - 443:443
    networks:
      - home-services
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

# NETWORKS
networks:

    home-services:
      driver: bridge
      name: home-services
      ipam:
        config:
          - subnet: 172.20.0.0/16
