---
version: "3.8"
services:
  nginx:
    image: docker-registry.theautomation.nl/coen/prd-nginx-certbot-app:latest
    container_name: prd-nginx-certbot-app
    restart: unless-stopped
    env_file: prd-nginx-certbot-app.env
    ports:
      - 80:80
      - 443:443
    networks:
      - home-services
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - prd-nginx-certbot-app:/etc/letsencrypt

# VOLUMES
volumes:
  prd-nginx-certbot-app:
    name: prd-nginx-certbot-app

# NETWORKS
networks:
  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16
